apiVersion: skaffold/v2beta4
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  tagPolicy:
    sha256: {}
  artifacts:
    # - image: adharshmk96/fiber_auth
    #   context: auth-fiber
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "**/*.go"
    #         dest: .
    - image: adharshmk96/gin_oauth
      context: oauth-gin
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.go"
            dest: .
    - image: adharshmk96/gin_auth
      context: auth-gin
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.go"
            dest: .