apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-fiber-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-fiber
  template:
    metadata:
      labels:
        app: auth-fiber
    spec:
      containers:
        - name: auth-fiber
          image: adharshmk96/fiber_auth
---
apiVersion: v1
kind: Service
metadata:
  name:  auth-fiber-srv
spec:
  type:  ClusterIP
  selector:
    app: auth-fiber
  ports:
    - name:  auth-fiber
      protocol: TCP
      port:  3000
      targetPort:  3000          
---   
### GIN auth app   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-gin-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-gin
  template:
    metadata:
      labels:
        app: auth-gin
    spec:
      containers:
        - name: auth-gin
          image: adharshmk96/gin_auth
---
apiVersion: v1
kind: Service
metadata:
  name:  auth-gin-srv
spec:
  type:  ClusterIP
  selector:
    app: auth-gin
  ports:
    - name:  auth-gin
      protocol: TCP
      port:  3001
      targetPort:  3001
